# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-tests',
                'doc_host': 'https://matheusdelg.github.io',
                'git_url': 'https://github.com/matheusdelg/nbdev-tests',
                'lib_path': 'nbdev_tests'},
  'syms': {'nbdev_tests.core': {'nbdev_tests.core.foo': ('core.html#foo', 'nbdev_tests/core.py')}}}
